### ISSUE TITLE
Default to 0.00 proximity for static resources?

### ISSUE THREAD

**Issue by tebemis** [nutella-framework/room-places-interface#2]
When adding static resources, is it possible to default the value of proximity to 0.00? Most of the times we won't be using it so it makes sense to have it "disabled" as a default.

**Comment by gianluca-venturini** [comment]
The idea behind static resource is that is able to track other resources (that must be marked as dynamic proximity). If you don't need the proximity radius you can use a dynamic-continuous resource, it will not have the proximity radius and it will not be automatically tracked by other static resources.

**Comment by tebemis** [comment]
But will I be able to specify its position? For instance, if I have an iMac (not tracking anything) and I want to put it on the map in a  specific location, I can't do that with dynamic resources, correct?

**Comment by gianluca-venturini** [comment]
You can do it, use this settings to track a dynamic resource manually:
![screen shot 2015-04-29 at 15 59 33](https://cloud.githubusercontent.com/assets/6535621/7401349/e9261744-ee88-11e4-8552-521c52c128e6.png)

**Comment by tebemis** [comment]
I see! Thanks for the clarification!
